# This is a basic workflow to help you get started with Actions

name: Distribute

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, feature/18-CI&CD ]
  pull_request:
    branches: [ main, feature/18-CI&CD ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      
      - name: Install bundle
        working-directory: ./LabProject/android
        run: |
          gem install bundle
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          
      - name: Create Firebase Service Credentials file
        working-directory: ./LabProject/android
        run: |
          echo "$FIREBASE_CREDENTIALS" > firebase_credentials.json.b64
          base64 -d -i firebase_credentials.json.b64 > firebase_credentials.json
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
          
      - name: Distribute app with 🔥 App Distribution 🚀
        working-directory: ./LabProject/android
        run: |
          ./gradlew clean && ./gradlew assembleRelease
          bundle exec fastlane deploy
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
